# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: scollet <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/01/11 17:26:30 by scollet           #+#    #+#              #
#    Updated: 2018/01/11 17:26:32 by scollet          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = frag
FILES = main.cpp FragTrap.cpp
INC = FragTrap.hpp
FLAGS = -Wall -Werror -Wextra
C = clang++

all:
	$(C) $(FLAGS) -I $(INC) $(FILES) -o $(NAME)
