# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: scollet <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/01/09 11:24:38 by scollet           #+#    #+#              #
#    Updated: 2018/01/09 11:24:39 by scollet          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = zombieHorde
FILES = main.cpp \
				ZombieHorde.cpp \
				Zombie.cpp
FLAGS = -Wall -Werror -Wextra
C = clang++

all:
	$(C) $(FLAGS) -I ZombieHorde.hpp $(FILES) -o $(NAME)
