# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: scollet <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/01/08 21:54:10 by scollet           #+#    #+#              #
#    Updated: 2018/01/08 21:54:12 by scollet          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = pony
FILES = Pony.cpp main.cpp
INC = Pony.hpp
FLAGS = -Wall -Werror -Wextra
C = clang++

all:
	$(C) $(FLAGS) -I $(INC) $(FILES) -o $(NAME)
