# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefie                                            :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: scollet <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/01/08 09:22:08 by scollet           #+#    #+#              #
#    Updated: 2018/01/08 09:22:47 by scollet          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = relevant_program
FILES = relevant_name.cpp
HEADER = relevant_header.hpp
FLAGS = -Wall -Werror -Wextra
C = clang++

all:
	$(C) $(FLAGS) -I $(HEADER) $(FILES) -o $(NAME)
