# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: scollet <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/01/18 14:24:06 by scollet           #+#    #+#              #
#    Updated: 2018/01/18 14:24:08 by scollet          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = array
FILES = main.cpp
FLAGS = -Wall -Werror -Wextra
INC = Array.hpp
C = clang++

all:
	$(C) $(FLAGS) -I $(INC) $(FILES) -o $(NAME)
