# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: scollet <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/01/10 16:50:55 by scollet           #+#    #+#              #
#    Updated: 2018/01/10 16:50:56 by scollet          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = fixed
FILES = Fixed.cpp
INC = Fixed.hpp
C = clang++
FLAGS = -Wall -Werror -Wextra

all:
	$(C) $(FLAGS) -I $(INC) $(FILES) -o $(NAME)
