# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: scollet <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/01/15 13:51:40 by scollet           #+#    #+#              #
#    Updated: 2018/01/15 13:51:41 by scollet          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = bureau
FILES = Bureaucrat.cpp main.cpp
INC = Bureaucrat.hpp
C = clang++
FLAGS = -Wall -Werror -Wextra

all:
	$(C) $(FLAGS) -I $(INC) $(FILES) -o $(NAME)
