# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: scollet <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/01/09 22:19:54 by scollet           #+#    #+#              #
#    Updated: 2018/01/09 22:19:55 by scollet          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = fiteNight
FILES = Weapon.cpp \
				HumanA.cpp \
				HumanB.cpp \
				main.cpp
FLAGS = -Wall -Werror -Wextra
C = clang++

all:
	$(C) $(FLAGS) -I Weapon.hpp $(FILES) -o $(NAME)
